spring.application.name=demo
# Configuração do Servidor (Spring Boot embutido usa 8080 por padrão)
# server.port=8080 # Se quiser mudar a porta
# server.servlet.context-path=/springbootlibrary # Se quiser um context path


spring.datasource.url=jdbc:h2:mem:livrosdb_sb;DB_CLOSE_DELAY=-1;NON_KEYWORDS=USER
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Para o console H2 (acessível em http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false

